spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/diablo2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: ypn7e0
springfox:
  documentation:
    swagger-ui:
      base-url: /documentation
    swagger:
      v2:
        use-model-v3: false
server:
  servlet:
    context-path: /diablo2
mybatis-plus:
  type-enums-package: com.cookiedoug.diablo2.enums